name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - fireflycons
body:
  - type: markdown
    attributes:
      value: |
        # Read This First!
        Thanks for taking the time to fill out this bug report!
        You should only use this form to report issues with deploying Kubernetes The Hard Way.
        Please *do not* use this form to ask questions about courses or exams, issues with courses, lecture requests etc.
        Use instead the KodeKloud Forum https://kodekloud.com/community/ as you will get a much faster answer there.
  - type: textarea
    id: workstation
    attributes:
      label: Your Workstation
      description: "Please tell us your PC/Mac/Laptop spec, for example:"
      placeholder: "Specification"
      value: Windows 10 Laptop, 16 GB RAM, 8 core i7 CPU
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant output
      description: Please copy and paste any relevant console output. This will be automatically formatted into code, so no need for backticks.
      render: shell